/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maps.lab;

import maps.lab.gates.gates;

public class App {

    public static void main(String[] args) {

        gates gate = new gates();

//        gate.fileReader();
        gate.filePathReader("gates");
    }
}
