/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Restaurant;

import Restaurant.Banking.Account;
import Restaurant.Banking.Member;

public class App {


    public static void main(String[] args) {
        banking();


    }
    public static void banking(){
        Member suhib = new Member("Suhib","Abbas", "Zarqa", "000-000-0000");
        suhib.openAccount(new Account(100));

        System.out.println("My balance is => " + suhib.getAccount().checkBalance());
    }
}
