/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import inheritance.RestaurantReview.Restaurant;
import inheritance.RestaurantReview.Review;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Restaurant restaurant = new Restaurant("Pro Restaurant" , 4);
        String testResult = restaurant.toString();

        assertEquals("Company{name='Pro Restaurant', star=4}",testResult);
        
    }
}
