/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lap02;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
    }

    @Test void rollTest(){

        int testResult = App.roll(5).length;
        assertEquals(5,testResult);
    }

    @Test void containsDuplicatesTest(){
        int[] test = {1,3,5,4,6,1};
        boolean testResult = App.containsDuplicates(test);
        assertTrue(testResult);
    }

    @Test void calculatingAveragesTest(){

        int[] test = {1,3,5,4,6,1};
                int testResult = App.calculatingAverages(test);
                assertEquals(3,testResult);
    }
    @Test void arraysAveragesTest(){
        int[][] arr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int testResult = App.arraysAverages(arr);
        assertEquals(57,testResult);
    }
}
