/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.lap02;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
    }

    @Test void rollTest(){

        int testResult = App.roll(5).length;
        assertEquals(5,testResult);
    }

    @Test void containsDuplicatesTest(){
        int[] test = {};
        boolean testResult = App.containsDuplicates(test);
        assertFalse(testResult);
    }

    @Test void calculatingAveragesTest(){

        int[] test = {1,3,5,4,6,1};
                int testResult = App.calculatingAverages(test);
                assertEquals(3,testResult);
    }
    @Test void arraysAveragesTest(){
        int[][] arr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] testResult = App.arraysAverages(arr);
        int[] expectedResult ={65, 56, 55, 52, 55, 62, 57};
        for(int index = 0; index < expectedResult.length;index++){
            assertEquals(expectedResult[index],testResult[index]);
        }

    }
    @Test void analyzingWeatherDataTest(){
        int[][] arr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        Set<Integer> expectedResult = new HashSet<>();

        expectedResult.add(67);
        expectedResult.add(68);
        expectedResult.add(69);
        expectedResult.add(63);

        Set<Integer> testResult =App.analyzingWeatherData(arr);

        assertEquals(expectedResult,testResult);

    }

    @Test void tallyTest(){
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String testResult =App.tally(votes);

        assertEquals("Bush", testResult);
    }
}
